apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: mvn-build-skip-tests
spec:
  inputs:
    resources:
    - name: tasks-git
      targetPath: /
      type: git
  steps:
  - name: build-install
    image: maven:3.6.0-jdk-8-slim
    command:
    - /usr/bin/mvn
    args:
    - |
      -s configuration/cicd-settings-nexus3.xml install -DskipTests=true
